include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

  errors:
    missing_return: error
    missing_required_param: error

  exclude:


linter:
  rules:
    avoid_renaming_method_parameters: true
    avoid_classes_with_only_static_members: false
    empty_catches: false
    overridden_fields: false
    use_setters_to_change_properties: false
